### REGISTER ROUTE TESTING
POST http://localhost:5200/api/user/register
Content-Type: application/json

{
  "name": "Sagar Bhat",
  "email": "sagar@fillkart.com",
  "password": "sagar123"
}


### LOGIN ROUTE TESTING

POST http://localhost:5200/api/user/login
Content-Type: application/json

{
  "email": "sagar@fillkart.com",
  "password": "sagar123sagar123"
}





### ADDING NEW PRODUCT
POST http://localhost:5200/api/products/admin/new
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NThiOWI1ZDUyNWNmM2U3ODUzM2VkMCIsImlhdCI6MTY4NDMxMzA2MSwiZXhwIjoxNjg0NzQ1MDYxfQ.nte6LxMloRsxTWeVqQ9WF-ZUJP7J2j0W2DZFlqi4ke4


{
  "name": "Clinic PLUS shampoo 250ml",
  "description": "Nothing just writing something to add something to description and what you guys will read it will be a total waste of time of yours please forgive me guys and then go to hell and you are even able to buy this what will you do in life chalo fir theek hain itna bakwaas kaafi hain description main",
  "price": 220,
  "imageUrl": "something.png",
  "category": "grocery"
}


### updating a product

PUT http://localhost:5200/api/products/admin/product/646488be47024fda107c0c80
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NThiOWI1ZDUyNWNmM2U3ODUzM2VkMCIsImlhdCI6MTY4NDMxMzA2MSwiZXhwIjoxNjg0NzQ1MDYxfQ.nte6LxMloRsxTWeVqQ9WF-ZUJP7J2j0W2DZFlqi4ke4

{
  "name": "Maggi Pasta Cheese Macaroni Pack Of 4 (70Gm * 4) Pasta  (Pack of 4, 280 g)",
  "description": "This is random text. Please don't read it . This is random text. Please don't read it. This is random text. Please don't read it. This is random text. Please don't read it. This is random text. Please don't read it. This is random text. Please don't read it.",
  "price": 49,
  "imageUrl": "https://rukminim1.flixcart.com/image/832/832/xif0q/pasta/t/i/q/280-pazzta-cheese-macaroni-pack-of-4-70gm-4-instant-4-maggi-original-imagh95p8vv2fm2g.jpeg?q=70",
  "category": "grocery"
}

###

GET http://localhost:5200/api/products/all



###

GET http://localhost:5200/api/products/product/646480dd47024fda107c0c4b

###

DELETE http://localhost:5200/api/products/admin/product/6464810847024fda107c0c51
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NThiOWI1ZDUyNWNmM2U3ODUzM2VkMCIsImlhdCI6MTY4NDMxMzA2MSwiZXhwIjoxNjg0NzQ1MDYxfQ.nte6LxMloRsxTWeVqQ9WF-ZUJP7J2j0W2DZFlqi4ke4


###

GET http://localhost:5200/api/user
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NThiOWI1ZDUyNWNmM2U3ODUzM2VkMCIsImlhdCI6MTY4NDMxMzA2MSwiZXhwIjoxNjg0NzQ1MDYxfQ.nte6LxMloRsxTWeVqQ9WF-ZUJP7J2j0W2DZFlqi4ke4

###

GET http://localhost:5200/api/products/product/search/ram
Content-Type: application/json

###

PUT http://localhost:5200/api/user/6469e3cdd37ee4d7d330bf3d
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NThiOWI1ZDUyNWNmM2U3ODUzM2VkMCIsImlhdCI6MTY4NDMxMzA2MSwiZXhwIjoxNjg0NzQ1MDYxfQ.nte6LxMloRsxTWeVqQ9WF-ZUJP7J2j0W2DZFlqi4ke4

{
  "role": "admin"
}


###

DELETE http://localhost:5200/api/user/6458a3606961f02fea106a70
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NThiOWI1ZDUyNWNmM2U3ODUzM2VkMCIsImlhdCI6MTY4NDMxMzA2MSwiZXhwIjoxNjg0NzQ1MDYxfQ.nte6LxMloRsxTWeVqQ9WF-ZUJP7J2j0W2DZFlqi4ke4


### add items to the cart

POST http://localhost:5200/api/cart/add
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ODc1NzE1N2QxNzE1ZmQzOTZjYzRlOCIsImlhdCI6MTY4NjU5MTI1MywiZXhwIjoxNjg3MDIzMjUzfQ.8LW-ggpbIwBTWhNjxVWEf-RXiePCcUUl-nGHI2vf1T4

{
  "productId": "6464800047024fda107c0c32"
}



### get all items from the cart

GET http://localhost:5200/api/cart/all
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ODc1NzE1N2QxNzE1ZmQzOTZjYzRlOCIsImlhdCI6MTY4NjU5MTI1MywiZXhwIjoxNjg3MDIzMjUzfQ.8LW-ggpbIwBTWhNjxVWEf-RXiePCcUUl-nGHI2vf1T4




### removing a product from cart

DELETE http://localhost:5200/api/cart/remove
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OGM4ODJhMGM0YmE1MzEwNjQ4OTQ4ZiIsImlhdCI6MTY4NzAyNTE3MiwiZXhwIjoxNjg3NDU3MTcyfQ.dvG64kOM0eEUNVPFjuudqQd2KZAo01HxgPdjCgujfn8

{
  "productId": "6464800047024fda107c0c32"
}


### stripe payment route

POST http://localhost:5200/api/stripe/create-checkout-session
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OGM4ODJhMGM0YmE1MzEwNjQ4OTQ4ZiIsImlhdCI6MTY4NzAyNTE3MiwiZXhwIjoxNjg3NDU3MTcyfQ.dvG64kOM0eEUNVPFjuudqQd2KZAo01HxgPdjCgujfn8

### stripe webhook

POST http://localhost:5200/api/stripe/webhook



### ORDER ROUTE

GET http://localhost:5200/api/order/all
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NThiOWI1ZDUyNWNmM2U3ODUzM2VkMCIsImlhdCI6MTY5MTA2Mzg2MSwiZXhwIjoxNjkxNDk1ODYxfQ.IIS2F8PizAkGsxAWB4kNEu-ePWRdroaNPZArTuIYS0M


### POST REVIEW
POST http://localhost:5200/api/products/review
Content-Type: application/json




### DELETE REVIEW

DELETE http://localhost:5200/api/products/review/6478667d9199d089266fe5cc
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZTFjZThjMDdjZTFmZDliMzQzNzQ3YyIsImlhdCI6MTY5Mjg2MzkxMiwiZXhwIjoxNjkzMjk1OTEyfQ.uVx1uUogPXXJ95Ii0KGstvqznSYlCv6feBZbyHmtBdg

{
  "reviewId": "64e645e554a422cc51b133f3"
}




